service: native-integrations
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt InventoryTable.Arn
functions:
  createRecord:
    handler: handlers/createRecord.handler
    environment:
      INVENTORY_TABLE: ${self:resources.Resources.InventoryTable.Properties.TableName}
plugins:
  - serverless-esbuild
  - serverless-step-functions

custom:
  esbuild:
    bundle: true
    exclude: []

stepFunctions:
  stateMachines:
    helloStateMachine:
      name: MyHelloStateMachine
      definition:
        StartAt: CreateDynamoDBRecord
        States:
          CreateDynamoDBRecord:
            Type: Task
            Resource:
              Fn::GetAtt: [createRecord, Arn]
            End: true
resources:
  Resources:
    InventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-registration-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
