service: sweet-factory
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt InventoryTable.Arn

functions:
  ingredientPreparation:
    handler: handlers/ingredientPreparation.handler
    environment:
      INVENTORY_TABLE: ${self:resources.Resources.InventoryTable.Properties.TableName}
  mixIngredient:
    handler: handlers/mixIngredient.handler
plugins:
  - serverless-esbuild
  - serverless-step-functions

stepFunctions:
  stateMachines:
    productionLineStateMachine:
      name: productionLineStateMachine
      definition:
        StartAt: IngredientPreparation
        States:
          IngredientPreparation:
            Type: Task
            Resource:
              Fn::GetAtt: [ingredientPreparation, Arn]
            Retry:
              - ErrorEquals:
                  - States.TaskFailed
                IntervalSeconds: 10
                MaxAttempts: 3
            End: true
resources:
  Resources:
    InventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-inventory-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: ingredient
            AttributeType: S
        KeySchema:
          - AttributeName: ingredient
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  esbuild:
    bundle: true
    exclude: []
